### ISSUE TITLE
A command-line client?

### ISSUE THREAD

**Issue by msiebuhr** [etsy/statsd#100]
I've submitted some stats from the command-line thusly:

```
echo "some.stat:`something_that_outputs_a_number`|g" | netcat -u -w1 statsd.example.com 8125
```

... but I can't quite figure out how to send the data without waiting one second (the `-w1` to `netcat`).

And wouldn't it be obvious to have a command-line client for doing ad-hoc mintoring of large batch-jobs and the like? (I considered rolling a CLI into `node-statsd-client`, but that requires Node.js, which isn't quite common to have installed.)

E.g. some variation of:

```
statsd-client [--gauge|--timer|--counter] [hostname] [--port 8125] <metric_name> <value|->
```

The `hostname` and `port` could be taken from the environment and the type could possibly be rolled into the `metric_name`.

**Comment by pataquets** [comment]
https://github.com/jondot/statsd-cli
