### ISSUE TITLE
mean_90 and upper_90 unclear

### ISSUE THREAD

**Issue by joshdevins** [etsy/statsd#157]
It's unclear from the documentation what the meaning of the two metrics mean_90 and upper_90 are on timers.

```
The percentile threshold can be a single value, or a list of values, and will generate the following list of stats for each threshold:

stats.timers.$KEY.mean_$PCT
stats.timers.$KEY.upper_$PCT
```

Is this the mean of the upper 90th percentile? What is upper_90 and how does it differ from plain old upper? Where is the mean metric then?

Looking through the code also does not elucidate.

**Comment by Guanpeng520** [comment]
Excuse me, what does std stand for?  

![image](https://user-images.githubusercontent.com/99166490/152741778-449126b2-85b1-454e-aed7-3085bd74ffd9.png)

**Comment by joshdevins** [comment]
@Guanpeng520 `std` refers to the standard deviation
