### ISSUE TITLE
generic enable/disable metrics

### ISSUE THREAD

**Issue by Dieterbe** [etsy/statsd#235]
many people want different things. also some backends (i.e. graphite) allow many runtime computations (and hence need fewer different metrics if one can be calculated from each other), here it makes sense to aim for keeping the carbon/whisper load lower.
other backends may be less advanced and having statsd store similar metrics becomes appropriate.

there should be a generic way to enable/disable certain metrics.
right now there's a bunch of issues/PR's where this is issue is treated for individual metrics, here are some of them:
#234 
#146

**Comment by mrtazz** [comment]
Thanks for submitting this. I think we could have a a pull request for a generic enable/disable which would also save time in the `process_metrics()` part if you are still interested in having this in StatsD.

**Comment by ttstarck** [comment]
No progress on this issue?
