### ISSUE TITLE
Memory growing over time?

### ISSUE THREAD

**Issue by alex-ethier** [etsy/statsd#241]
Hi,

We noticed that node memory is growing over short period of time (Triple over few days)
The only node process running on the server is statsd.  Is this normal?

Thanks
A

**Comment by idling11** [comment]
@mrtazz  I found that  when i use  statsd_proxy, the  memory usage of  the process increase always。Finally,  get an  OOM error !  The error stack as below:
<--- Last few GCs --->

[60644:0x2f2ba10]   782598 ms: Scavenge 1100.6 (1142.3) -> 1087.7 (23819.3) MB, 100.3 / 2.6 ms  allocation failure
[60644:0x2f2ba10]   784577 ms: Mark-sweep 1087.7 (23820.3) -> 935.1 (23764.8) MB, 1977.7 / 13.2 ms  allocation failure GC in old space requested
[60644:0x2f2ba10]   787327 ms: Mark-sweep 951.5 (23764.8) -> 936.9 (23760.8) MB, 1916.0 / 11.4 ms  allocation failure scavenge might not succeed


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: node::Abort() [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 2: 0x126264c [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 5: 0xa64d9b [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 6: v8::internal::MarkCompactCollector::EvacuateNewSpaceAndCandidates() [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 8: v8::internal::Heap::MarkCompact() [/home/da_music/node-v7.2.1-linux-x64/bin/node]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
10: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
11: v8::internal::Factory::NewJSObject(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::PretenureFlag) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
12: v8::Object::New(v8::Isolate*) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
13: node::AddressToJS(node::Environment*, sockaddr const*, v8::Local<v8::Object>) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
14: node::UDPWrap::OnRecv(uv_udp_s*, long, uv_buf_t const*, sockaddr const*, unsigned int) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
15: 0x15126af [/home/da_music/node-v7.2.1-linux-x64/bin/node]
16: 0x15146c8 [/home/da_music/node-v7.2.1-linux-x64/bin/node]
17: uv_run [/home/da_music/node-v7.2.1-linux-x64/bin/node]
18: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
19: node::Start(int, char**) [/home/da_music/node-v7.2.1-linux-x64/bin/node]
20: __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
21: 0x8bc5d1 [/home/da_music/node-v7.2.1-linux-x64/bin/node]

Could you tell me why this happend?  appreciate it 
Lee
