### ISSUE TITLE
Statsd - UDP - Data Loss - 

### ISSUE THREAD

**Issue by RajanBhatt** [etsy/statsd#245]
Hello,

I would be inclined to know data loss observed in data center using Statsd which is a UDP based. What decision rationale was used leveraging UDP instead of TCP ? 
Has anybody observed significant data loss in data center using Statsd ?
Any suggestion and thought on these issue is highly appreciated,

Thanks
Rajan

**Comment by hit9** [comment]
cc https://github.com/hit9/statsd-proxy

**Comment by RajanBhatt** [comment]
Thanks Chao. Appreciate it.Let me check it out Regards Rajan Bhatt 


     On Thursday, September 10, 2015 7:19 AM, Chao Wang <notifications@github.com> wrote:
   
 

 cc https://github.com/hit9/statsd-proxy—

**Comment by hit9** [comment]
@RajanBhatt :smile: We meet the same problem, and we are now using this statsd-proxy.

Maybe you also want to checkout the following projects:

- http://githubengineering.com/brubeck/

**Comment by RajanBhatt** [comment]
Your are kind...Let me check out and thanks again for brubeck link...Keep in touch Regards Rajan Bhatt 


     On Thursday, September 10, 2015 7:58 AM, Chao Wang <notifications@github.com> wrote:
   
 

 @RajanBhatt  We meet the same problem, and we are now using this statsd-proxy.Maybe you also want to checkout the following projects:   
   - http://githubengineering.com/brubeck/
