### ISSUE TITLE
RFC: Support forked backend model

### ISSUE THREAD

**Issue by mheffner** [etsy/statsd#281]
Any thoughts on supporting a model where backend modules are started in a forked process? Metrics would be pushed to the backends over an established pipe, allowing backends to process/post measurements with less impact to the main statsd daemon. For low flush periods, are there any metrics on time drift from backend processing?

The backend pipe should be set non-blocking to prevent statsd from blocking while flushing metrics to a backend that is not able to keep up. Open question is whether the daemon should drop metrics if a backend pipe is blocked over some threshold of time.

**Comment by mrtazz** [comment]
After thinking about this and having played with statsite's implementation of this, I don't think we should do this. We would need to add another serialization/deserialization step into StatsD and I don't think the benefit of writing backends in a different language outweighs the cost of that step.
