### ISSUE TITLE
Inaccurate aggregation with example Graphite retention scheme

### ISSUE THREAD

**Issue by aboks** [etsy/statsd#302]
According to the [Whisper documentation](http://graphite.readthedocs.org/en/1.0/whisper.html#archives-retention-and-precision), the number of points in a retention archive must be divisible by the number of points in the previous retention archive to have accurate aggregation.

The example storage schema in https://github.com/etsy/statsd/blob/master/docs/graphite.md#storage-schemas specifies a retention policy of `10s:6h,1min:7d,10min:5y`, which gives
- 2160 points of 10s-data
- 10080 points of 1min-data
- 262800 points of 10min-data

However, 262800 is not divisible by 10080, nor is 10080 divisible by 2160, so this scheme causes inaccuracies when data is rolled up.

Maybe it's best to change the example retention schema to something like `10s:7h,1min:1w,10min:260w` or `10s:7h,1min:1w,10min:270w`, where 260 weeks is just short of 5 years and 270 weeks a bit more than 5 years.

**Comment by ksingh7** [comment]
Thanks @aboks @tomsutton1984 , referred this issue and found solution to my very annoying problem.
