### ISSUE TITLE
Feature request: post absolute counter value

### ISSUE THREAD

**Issue by mfischer-zd** [etsy/statsd#324]
Clients should be able to post counters in "absolute" mode, by which I mean that posting 12345 to a counter metric should be treated as "the value of this counter is currently 12345".  (Currently you can only increment or decrement a counter.) Wraparounds should be handled by statsd when calculating derivations.

This will make it much easier to retrieve counters from foreign sources (e.g., OS or network device statistics from SNMP etc.) and submit them to statsd as-is before backposting them to a metrics graphing/aggregation service.  Without this functionality, the client must maintain state and post deltas themselves, at which point we might as well use a gauge.

**Comment by mrtazz** [comment]
Closing this since I think adding this to counter will blur the lines between gauges and counters even more. And posting absolute values is still a feature supported by gauges. So if you are setting a value and are not actually counting things, using a gauge should be the way to go.
