### ISSUE TITLE
Feature request: support for multiple graphite backends

### ISSUE THREAD

**Issue by yvesjans** [etsy/statsd#341]
We have a setup where we send monitoring data to two datacenters to have redundancy in case of an outage (collectd network plugin with multiple servers)

Would it be possible to add support to statsd for multiple graphite backends in the configuration file so that data will flow to two graphite backends in parallel ?

**Comment by rewolf** [comment]
@mrtazz Did this ever happen?  Would it be equivalent to setup multiple statsD daemons, one for each backend, and then a separate statsD repeater daemon that would send to each of those?

**Comment by maradwan** [comment]
@anton-rudeshko  did you make it ?

**Comment by anton-rudeshko** [comment]
Sorry, I'm really do not remember much. Apparently there was no PR from me.
We've tried statsd and not used it in production.
