### ISSUE TITLE
Add "main": "stats.js" To package.json

### ISSUE THREAD

**Issue by wesleytodd** [etsy/statsd#353]
This would enable loading statsd into another application using `require`.  The specific feature I would like to use is `require.resolve('statsd')` to get the direct path to the install so I can wrap it in an application I am writing.

On a similar note, it seems like it might be nice to have a method for starting a statsd server programmatically, but that is a side note here.

Thoughts?

**Comment by mrtazz** [comment]
I like the idea of this and it's gonna take some refactoring in the current code base. If you're up for sending this as a pull request I'm happy to work with you on getting it merged.

**Comment by wesleytodd** [comment]
While I still think this is a good idea for the project, my company has moved away from statsd and written our own stats platform in go.  So I have not even looked at this in quite a while.  Thanks for responding, but I don't think I will be able to PR this in.
