### ISSUE TITLE
Java statsd example does not close channel

### ISSUE THREAD

**Issue by JensRantil** [etsy/statsd#358]
I just noticed that [`_channel`](https://github.com/etsy/statsd/blob/master/examples/StatsdClient.java#L61) is not closed. Unless the class is used as a singleton, there will be file leaks until garbage collection.

**Comment by mrtazz** [comment]
Nice catch, I'm happy to merge a pull request that fixes this.

**Comment by JensRantil** [comment]
Maybe keep this issue open unless there's a fix for this merged in?
