### ISSUE TITLE
TODO: Configurable Encoding

### ISSUE THREAD

**Issue by draco2003** [etsy/statsd#374]
toString and new Buffer both can be passed an encoding type. If you aren't using non-ascii characters for metrics there is performance gains to be had.

toString:
https://github.com/etsy/statsd/blob/master/proxy.js#L40
https://github.com/etsy/statsd/blob/master/proxy.js#L52

new Buffer
https://github.com/etsy/statsd/pull/373/files#diff-ba25ea553e3ff05620224368284e4ae3R51

**Comment by mrtazz** [comment]
the new buffer one was merged. closing this.
