### ISSUE TITLE
TODO: Configurable enable/disable of last_msg_seen

### ISSUE THREAD

**Issue by draco2003** [etsy/statsd#375]
If you aren't using this metric, than it is a lot of overhead per packet received and disabling it for a busy statsd process has performance gains.

https://github.com/etsy/statsd/blob/master/stats.js#L246

Would be great to add a configuration flag to enable/disable this

**Comment by mrtazz** [comment]
I don't think we are gaining that much from this. I think calculating a timestamp once per packet is probably less work than everything else we do.
