### ISSUE TITLE
Key sanitization

### ISSUE THREAD

**Issue by allevo** [etsy/statsd#430]
I'd like use statsd to check the performance of a nginx server (through LUA).

As a key, I'm using [uri].[method].[http status code]
During my tests, I notice the key stored in the daemon isn't correct because the key is sanitized replacing some character at https://github.com/etsy/statsd/blob/master/stats.js#L189

I'd like to know if this behavior is requested or the graphite backend requires this sanitization.

My backend will not be graphite but ElasticSeach (http://www.elasticsearch.org/).

**Comment by pathzzrd** [comment]
@allevo, we just merged #451 which optionally moves the sanitization to the specific backend. You can disable sanitization by setting keyNameSanitize to false in the config
