### ISSUE TITLE
How do I clamp timestamp to precise at 10s internals. E.g. 04:00s, 04:20s, 04:30s, 04:40, etc

### ISSUE THREAD

**Issue by ankitjaininfo** [etsy/statsd#459]
I tried stats and find that the time intervals are not aligned to absolute 10s, 20s, 30s, etc. We are planning to use it for 60s interval and wish to clamp if around start of the minute. That way it appears correct in plotted graphs. Looking at the following line it does appear possible without changing signification code.

```js
var flushInt = setInterval(flushMetrics, flushInterval);
```

My approach for doing this is to compute and create `current` and `next` buckets to hold metrics. Whenever a new metric comes, either it goes in current or next bucket. If goes in next, current should be flushed and next becomes current.

Let me know if there is an existing better way to achieve this.

**Comment by mrtazz** [comment]
I'm not sure what problem this solves. We could always mod the timestamp to the precise interval. However Graphite already records things at that interval. So if a different backend needs that functionality it should probably be implemented in that backend.
