### ISSUE TITLE
cut v0.8.0 release

### ISSUE THREAD

**Issue by mrtazz** [etsy/statsd#463]
with the addition of the server interface we should cut a release so there can be sane dependency requirements for people when they write additional interfaces  (e.g. there is already https://github.com/msiebuhr/statsd-http-interface). I added a milestone (https://github.com/etsy/statsd/milestones/v0.8.0) so we can track bugs we definitely want to fix and include in the release.

**Comment by afelle1** [comment]
What is the time frame on this?  Little concerned since last official release was Feb 2014.

**Comment by josegonzalez** [comment]
beep :)

**Comment by Zeelot** [comment]
boop!?

**Comment by mulloymorrow** [comment]
#bop

**Comment by pathzzrd** [comment]
boip!

Very busy but I am currently working towards getting this out. It will include a fix for #462 and also some cleanup. I will post a link to the PR soon.

**Comment by neonstalwart** [comment]
@pathzzrd i'm considering doing some work on #462 and #339 (could you add this to the 0.8 milestone too?) but don't want to duplicate anything that may already be happening.  do you have anything started for these already or want to give some input about how you'd like them fixed?

**Comment by pathzzrd** [comment]
@neonstalwart First, sorry for the delay. I started on a fix for #462 sometime ago by attempting to pull the admin telnet interface out into its own module. I have since scrapped the code. I think that the real solution here is a large refactor of the admin interface. I'd welcome any help/opinions on this.

**Comment by neonstalwart** [comment]
@pathzzrd thanks for the response.  to tell you the truth, i've ended up writing directly to influxdb for my very basic needs so i won't have time to put any effort into statsd.  thanks.

**Comment by NoodlesNZ** [comment]
*bump*
Is this getting any closer?

**Comment by mulloymorrow** [comment]
Doesn't sound like it will happen.

**Comment by afelle1** [comment]
Can always migrate to https://github.com/armon/statsite.  Found performance much better

**Comment by draco2003** [comment]
In case statsite doesn't fit your needs there is also another one released
jun 15th from Github:
https://github.com/github/brubeck

**Comment by genuss** [comment]
Beware of brubeck issue https://github.com/github/brubeck/issues/16

**Comment by fde31** [comment]
Is it possible to get any info here? I'm interested in using the new multi-server support for TCP and UDP and yeah not 100% sure if I should wait for the 0.8.0 release given the fact that time has definitely passed by since Oct 21. What's the recommended procedure? Also in more broader terms, how stable is the master branch?

**Comment by afelle1** [comment]
I'd have to confirm what snapshot we tried but the proxy support didn't really help any.  We switched to statsite though I imagine you could deploy statsd to every box where services are running and have them report to statsd suffixed by the boxes' hostname.  This would work in a way I've seen codahale metrics library working for Java projects.

**Comment by pathzzrd** [comment]
beep

**Comment by josegonzalez** [comment]
Beep! https://github.com/etsy/statsd/releases/tag/v0.8.0 :)
