### ISSUE TITLE
What is best way to deal with Late Arrival Events ?

### ISSUE THREAD

**Issue by bmistry13** [etsy/statsd#464]
Hi Dev Team,

Can you please give suggestion how we can deal or suggestion how we can modify statsd code to handle following issues ?

1)	How do flush every minute at minute level 0,1,2,3,4,5…..59 like crown to get more accurate accounting from our application because every minute we flush metric to Graphite so we need to have flush every minute at 0,1,2….59 for accuracy for that minute.

2)	Data Arriving at late or aggregating at Time Stamp Level rather than current minute bucket ?  We have data pipe-line and event can get delayed upto 5 minutes so we discarded and counted for current minute so is there any way to aggregate at time stamp level and metric name.

3)	Also, when StatsD starts/restart then is it possible to pull last X minute buckets data from Graphite for accurate counting when StatsD is redeployed or started.

I know the intend of StatsD is to aggregate on current minute (real time event), but what it will take to achieve aggregation of past buckets ?

Thanks,

Bhavesh

**Comment by mrtazz** [comment]
For flushing every minute you can just set the [config entry](https://github.com/etsy/statsd/blob/master/exampleConfig.js#L36) to flush every minute. Aggregating data that is arriving late is not possible in StatsD and given that it would mean a big rewrite of the current implementation it's also not really in scope to be added any time soon. I don't think it makes sense to try to get data from Graphite into StatsD. StatsD operates within the notion of a flush interval. No values are carried over from flush intervals (usually) so there shouldn't be a need to get data from Graphite for any of the calculations StatsD does.
