### ISSUE TITLE
Statsd process per client host

### ISSUE THREAD

**Issue by kqazi** [etsy/statsd#466]
We are thinking of running statsd on every client host in the attempt to work past UPD packet loss issues we have faced in both running a single statsd host which all clients use and with using the cluster-proxy (which just seemed to push the packet loss to the proxy).

That said, are there any best practices when moving to a statsd per host model that we need to pay special attention to?  For example it would seem mandatory to prefix metrics with the host name to avoid metric collisions between the multiple hosts of the same application (cluster) emitting the same metric.  

Any pointers are appreciated.

**Comment by mrtazz** [comment]
afaik making sure you prefix the stats namespaces is the only big thing. We are still running StatsD centrally so I can't really talk more about this.
