### ISSUE TITLE
Raw metrics are treated as invalid messages.

### ISSUE THREAD

**Issue by fizyk** [etsy/statsd#467]
I'm using python-statsd to send out metrics to statsd, and one of metrics used us raw metric type: https://python-statsd.readthedocs.org/en/latest/statsd.raw.html

However when sending this metric, I'm getting following error:

```
23 Oct 11:29:22 - DEBUG: Bad line: 0.0,r,1414063200 in msg "metric_name:15.0|r|1414063200"
```

I believe it would be passed on before this change:
https://github.com/etsy/statsd/commit/63fb16ceeaa278305f3dee09b66db166a31e6ab2

Right now I'm forced to mock to pass the message through (add @ to timestamp and pass it as a string) But still value is not passed And I'm not sure if it's because of wrong timestamp then?

**Comment by mrtazz** [comment]
this is not  supported metric type in statsd. See https://github.com/etsy/statsd/blob/master/docs/metric_types.md
