### ISSUE TITLE
statsd crash when a tcp rst packet came

### ISSUE THREAD

**Issue by jdlindu** [etsy/statsd#471]
In my situation ,  keepalived will send a tcp request to check the health of statsd server on port 8125 every few second

<pre><code>
admin@239-175:/opt/statsd$ cat localConfig.js
{
graphitePort: 2003
, graphiteHost: "192.168.1.2"
, server: "./servers/tcp"
, port: 8125
, backends: [ "./backends/graphite" ]
, debug: true
}

admin@239-175:/opt/statsd$ node stats.js localConfig_tcp.js 
28 Oct 19:33:09 - reading config file: localConfig_tcp.js
28 Oct 19:33:09 - DEBUG: Loading server: ./servers/tcp
28 Oct 19:33:09 - server is 
28 Oct 19:33:09 - DEBUG: Loading backend: ./backends/graphite
28 Oct 19:33:09 - DEBUG: numStats: 2

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
admin@239-175:/opt/statsd$ 
</code>

**Comment by justmywyw** [comment]
I have the same problem,how do you fix it?
