### ISSUE TITLE
Make it possible to use unicode/non-ascii characters in keys

### ISSUE THREAD

**Issue by tilmans** [etsy/statsd#474]
Graphite supports unicode in key names (https://github.com/graphite-project/graphite-web/pull/480) and we are using this feature. StatsD is stripping a lot of characters from the key which makes mapping back very hard.

Please consider adding on option to turn this off or make the regex accept unicode characters.

The corresponding line in stats.js:

                var key = bits.shift()
                      .replace(/\s+/g, '_')
                      .replace(/\//g, '-')
                      .replace(/[^a-zA-Z_\-0-9\.]/g, '’);

**Comment by pathzzrd** [comment]
We just merged #451 which includes the ability to turn off key name sanitization. You can do so by setting keyNameSanitize to false in the config.
