### ISSUE TITLE
How to collect cpu/memory/disk/network utiliziation for statsd consumption?

### ISSUE THREAD

**Issue by fbm-static** [etsy/statsd#481]
Hi,

I'm sorry if this is a bit off-topic. But I have no idea how to collect cpu/memory/disk/network usage so I can send them statsd. Is there a script that can do that? Or maybe a repo of bash scripts to parse various  command outputs and send them to statsd? I've tried searching here @ github with the keyword `statsd` but mostly I find are clients.

I hope you (who are reading this) can help. Thanks!

**Comment by genuss** [comment]
You could check out [collectd](http://collectd.org). It has statsd plugin to send metrics.

**Comment by fbm-static** [comment]
@genuss their statsd plugin does not write to a statsd server but instead will create a statsd-like server.

**Comment by mrtazz** [comment]
Yea it does. But for this use case I would still recommend using collectd and send to graphite directly. Most of the system level metrics probably don't really fit the counter or timing paradigm anyways. Or are you looking to get something specific out of using StatsD for this?

**Comment by fbm-static** [comment]
@mrtazz not really. Thanks!
