### ISSUE TITLE
statsd ignores packets

### ISSUE THREAD

**Issue by amosshapira** [etsy/statsd#482]
I'm trying to setup statsd in a pretty straight-forward configuration but statsd fails to process even a single packet in a simple test:
1. Ubuntu 14.04 LTS x64 on EC2 instance
2. statsd installed from either github "master" branch or the latest release 0.7.2, packaged into a debian package.
3. nodejs version is v0.10.25 (from Ubuntu package)

I'm concentrating on statsd since I narrowed things down to it not sending the data to collectd
To test it:
* I point it to an alternative TCP port with socat showing what statsd sends to collectd: `socat -v -d -d -lf/root/socat.log TCP4-LISTEN:2000,bind=0.0.0.0,reuseaddr,fork TCP4-CONNECT:localhost:2003,bind=0.0.0.0`
* For completness, here is the content of /etc/statsd/localConfig.js:
```
{
  graphitePort: 2000
, graphiteHost: "localhost"
, port: 8125
, legacyNamespace: false
, dumpMessages: true
}
```
* I verified that statsd listens on UDP port 1825 on any interface: `udp        0      0 0.0.0.0:8125            0.0.0.0:*                           26258/statsd    ` 
* I tcpdump on statsd UDP socket: `tcpdump -A -i any udp port 1825`
* I send a packet using socat: `echo "sample.gauge:14|g" | socat - udp:localhost:1825`
* I see the packet arriving to the port which is listened on by statsd:
```
01:24:48.995975 IP localhost.53349 > localhost.1825: UDP, length 18
E.....@.@.o..........e.!...-sample.gauge:14|g
```
* statsd keeps reporting "0 packets received" (if I correctly interpret the meaning of `stats_counts.statsd.packets_received 0 1421285211`), Here is a full data transmission from statsd to graphite:
```
> 2015/01/15 01:26:50.740376  length=586 from=0 to=585
stats.statsd.bad_lines_seen 0 1421285211
stats_counts.statsd.bad_lines_seen 0 1421285211
stats.statsd.packets_received 0 1421285211
stats_counts.statsd.packets_received 0 1421285211
stats.gauges.statsd.timestamp_lag 0 1421285211
statsd.numStats 3 1421285211
stats.statsd.graphiteStats.calculationtime 0 1421285211
stats.statsd.processing_time 0 1421285211
stats.statsd.graphiteStats.last_exception 1421279195 1421285211
stats.statsd.graphiteStats.last_flush 1421285201 1421285211
stats.statsd.graphiteStats.flush_time 0 1421285211
stats.statsd.graphiteStats.flush_length 586 1421285211
```

Once in a blue moon, it actually processes a packet and adds the sample gauge to the data it sends to graphite, but then it doesn't process any later updates and keeps sending the old value.

I verified that there are no iptables rules blocking it. I also checked in /proc/net/udp that no packets were dropped.

What else am I missing?

Thanks.

**Comment by amosshapira** [comment]
I've found the following bug report about the netcat-freebsd which I was using to generate the test UDP traffic: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747646

I verified that the extra "X"'s appear when I repeat the example in the bug.

Switching to using "socat", like this: 'echo "sample.gauge:4|g" | socat - udp:localhost:8125', started to send data to statsd which promptly updated its stats (or at least sent the right expected output to collectd).

I'm not 100% this is related since, as you can see in the tcpdump above, the "X"'s didn't appear in tcpdump, but it might still be the issue.

**Comment by afelle1** [comment]
Aside from confusion from use of 1825 vs 8125 and without looking at your carbon.conf / storage_aggregation.conf, it sounds like you haven't [adjusted xFilesFactor](http://graphite.readthedocs.org/en/latest/config-carbon.html) for sparse data.  It's clear from your testing that statsd is working but the data isn't showing in graphite.

**Comment by amosshapira** [comment]
statsd most of the time (except very rarely) didn't report any of the data I sent it and when it did, it didn't update it. This is clear from the snooping on the tcp connection from statsd to carbon. Once I switched to a different tool everything worked as expected (I left it running overnight and it worked fine). I'll close this issue since it was fixed with a test tool change.
