### ISSUE TITLE
statsd to point graphite and influxdb

### ISSUE THREAD

**Issue by karthiklml** [etsy/statsd#483]
Hi, 
I am using statsd to send the metrics to graphite.  my new requirement is from statsd like to send the metrics to graphite as well to influxdb . 

Please share the config.js format. 

Thanks

**Comment by nishansubedi** [comment]
Hey @karthiklml http://www.symantec.com/connect/blogs/metrics-cocktail-statsdinfluxdbgrafana this blog post seems to have a good example of the config format for influxdb.

**Comment by karthiklml** [comment]
@nishansubedi ,

Thanks for your update , my requirement is little different . 

We are having both setup 
statsd => graphite => whisper => grafana
statsd => influxDB => grafana 

My requirement is I want to push the data from the single statsd daemon to both setup. 

Thanks .

**Comment by mrtazz** [comment]
You can use multiple backends in StatsD [like this](https://github.com/etsy/statsd/blob/master/exampleConfig.js#L17) and they will both get the metrics on flush time. And there is a third party backend available and listed in [the wiki](https://github.com/etsy/statsd/wiki/Backends).
