### ISSUE TITLE
What use are the non-rate counts?

### ISSUE THREAD

**Issue by DandyDev** [etsy/statsd#487]
In the documentation about using Graphite as backend, it says the following about the ways StatsD sends _count_ values to Graphite:
> per-second counts under stats.counters.<name>.rate, and non-normalized per-flush counts under stats.counters.<name>.count. 

It seems to me that the `.rate` data is much more useful than the _non-normalized per-flush counts_. With the latter, you would have to keep in mind the flush interval every time you view a graph in Graphite of that data. So when I look at the default graph for a non-normalized count in Graphite and it shows that around 20:00 it shows as "400", it means that there were 400 events _per 10 seconds_ around that time, not per second, as I would expect.

What I'm trying to figure out, is: how are non-rate counts (non-normalized per flush counts) useful? In a Graphite graph you are always looking at data in a time-based context (it's time-series data after all), so per second data makes much more sense, instead of having to worry about your flush interval.

Another question about "per-flush" -> is this tied to the flush interval as configured in StatsD, or also the storage interval as configured in Graphite?

**Comment by Dieterbe** [comment]
i think you're spot on re non-normalized counts. the only thing i've seen them being good for is confusing people and letting people mistakenly create broken graphs. I never use them and recommend people to stay away from them. (in my statsd server, https://github.com/vimeo/statsdaemon they're not even emitted)

> Another question about "per-flush" -> is this tied to the flush interval as configured in StatsD
statsd flush interval.

of course in practice they're probably the same, and having a different graphite interval may lead to other problems as well (this is described somewhere in the docs/readme)

**Comment by DandyDev** [comment]
Thanks for the clarification/confirmation! I'm also gonna have a look at statsdaemon :)

**Comment by Wolf480pl** [comment]
IMO per-flush counts would be useful if you wanted to use a sum aggregation in graphite.
