### ISSUE TITLE
backend for couchdb

### ISSUE THREAD

**Issue by sysadminmike** [etsy/statsd#491]
Hi 

In case this is useful for anyone else have made a backend for couchdb:
https://github.com/sysadminmike/couch-statsd-backend

Mike.

**Comment by mrtazz** [comment]
That's awesome! Can you send a pull request to add it to [the docs](https://github.com/etsy/statsd/blob/master/docs/backend.md) and add it to [the wiki page](https://github.com/etsy/statsd/wiki/Backends)? Thanks!

**Comment by sysadminmike** [comment]
pr for backend doc sent
