### ISSUE TITLE
"make" failed with exit code 2

### ISSUE THREAD

**Issue by sergei1152** [etsy/statsd#492]
Hey I'm getting errors when trying to install statsd and it's dependencies. It seems to be an error with make. *I'm running SUSE 11 with node.js 0.12 installed. *
```
make: *** [Release/obj.target/syslog/syslog.o] Error 1
make: Leaving directory `/home/nodebot/svt-tool/node_modules/statsd/node_modules/node-syslog/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodebot/IBMSVT64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.0.101-0.40-default
gyp ERR! command "node" "/home/nodebot/IBMSVT64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodebot/svt-tool/node_modules/statsd/node_modules/node-syslog
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> hashring@1.0.1 install /home/nodebot/
```

**Comment by mrtazz** [comment]
this should work again now. Please reopen if it doesn't.

**Comment by sergei1152** [comment]
Hey I'm still getting the same issue when trying to do an npm install inside the statsd directory:

```
nodebot@jtcjs09:~/sergeTest/statsd$ npm install
|
> node-syslog@1.1.7 install /home/nodebot/sergeTest/statsd/node_modules/node-syslog
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/nodebot/sergeTest/statsd/node_modules/node-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../node-syslog.h:13:0,
                 from ../syslog.cc:1:
../compat.h:127:21: error: ‘compat::ReturnType compat::ReturnableHandleScope::Return(int)’ cannot be overloaded
   inline ReturnType Return(int value);
                     ^
../compat.h:126:21: error: with ‘compat::ReturnType compat::ReturnableHandleScope::Return(intptr_t)’
   inline ReturnType Return(intptr_t value);
                     ^
In file included from ../syslog.cc:2:0:
../compat-inl.h:127:12: error: redefinition of ‘compat::ReturnType compat::ReturnableHandleScope::Return(int)’
 ReturnType ReturnableHandleScope::Return(int value) {
            ^
../compat-inl.h:123:12: error: ‘compat::ReturnType compat::ReturnableHandleScope::Return(intptr_t)’ previously
defined here
 ReturnType ReturnableHandleScope::Return(intptr_t value) {
            ^
make: *** [Release/obj.target/syslog/syslog.o] Error 1
make: Leaving directory `/home/nodebot/sergeTest/statsd/node_modules/node-syslog/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodebot/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/home/nodebot/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodebot/sergeTest/statsd/node_modules/node-syslog
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing node-syslog@1.1.7
```

**Comment by tamirlancomas** [comment]
please help me
i wanna install to pigsty-moloch-plugin

npm install https://github.com/hillar/pigsty-moloch-plugin/archive/master.tar.gz

but ..
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-33-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/user/pigsty-moloch-plugin/node_modules/hashtable
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! hashtable@1.0.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@1.0.0 install script.
npm ERR! This is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/pigsty-moloch-plugin
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by peichao01** [comment]
me the same Error on `Ubuntu@14.04desktop & node@0.12.3 & npm@2.10.0 & node-gyp@1.0.3`.   
search and test more than two days and not resolved.

	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
	gyp ERR! System Linux 3.16.0-37-generic
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/peichao/test_npm_cpp_module/node_modules/statsd/node_modules/node-syslog
	gyp ERR! node -v v0.12.3
	gyp ERR! node-gyp -v v1.0.3
	gyp ERR! not ok

**Comment by deepanprabhu** [comment]
I also got this very same issue, Kind of hindering progress. If anyone has a solution, please post !!
