### ISSUE TITLE
Debian init script : stop action kills every other node process on the system

### ISSUE THREAD

**Issue by arnaudmm** [etsy/statsd#497]
File : https://github.com/etsy/statsd/blob/master/debian/statsd.init

To fix bug, remove lines 92 and 93

**Comment by lghamie** [comment]
Found the same issue today, but the script is not there anymore. Why's that? no more init.d support?

**Comment by arnaudmm** [comment]
I guess they moved for systemd (jessie). So only .service file available.

**Comment by lghamie** [comment]
Yeah but I'm running Debian 7. Well, i applied your fix and it seems to work. Removing those lines has any side-effect?

**Comment by benburry** [comment]
Thanks for pointing this out. As the debian support was a contribution, and the sysv script has been replaced by an upstart one, I'm closing this
