### ISSUE TITLE
debian packages comes with init.d and upstart .. why?

### ISSUE THREAD

**Issue by tolleiv** [etsy/statsd#500]
Hi,
Atm it seems that you ship init.d and upstart init scripts within the debian package and this is at least confusing for users. I was wondering whether sending a pull request with the upstart compatible init scripts (see https://wiki.ubuntu.com/UpstartCompatibleInitScripts ) would make sense from your point of view.

Cheers

**Comment by tuxinaut** [comment]
With #506 the **init.d** script is gone but I think that the upstart script is upstart only.

**Comment by roflmao** [comment]
This breaks debian package since systemd doesnt have compat with upstart as with sysvinit.
So this will work for Ubuntu but not for Debian.

**Comment by roflmao** [comment]
#532

**Comment by tolleiv** [comment]
Right so I'd say this one can be closed.
Thanks for the feedback & fixes :)
