### ISSUE TITLE
Please update Changelog.md and debian/changelog files 

### ISSUE THREAD

**Issue by tehmaspc** [etsy/statsd#502]
Please (re) start updating the StatsD changelog.md and debian/changelog files.
This is super helpful when building pkgs of statsd - esp. in the way described in this issue:
https://github.com/etsy/statsd/issues/161

**Comment by tuxinaut** [comment]
See also #506

**Comment by mrtazz** [comment]
closed with https://github.com/etsy/statsd/pull/506
