### ISSUE TITLE
Hashring 3.1.0 breaks proxy.js on node v0.10.25

### ISSUE THREAD

**Issue by ktheory** [etsy/statsd#503]
I had some trouble running statsd proxy from 23b33189.

I was using an Ubuntu 14.04 server with the stock nodejs & npm versions (`apt-get install -y nodejs npm`).

When I ran `proxy.js` with 2 workers, every metric I sent was dropped with the error:

```
Warning: No backend statsd nodes available!
```

I knew my workers were healthy, b/c they were responding to the health check. And I could see them being added/removed in the proxy logs as I stopped/started them:

```
Removing node 127.0.0.1:8126 from the ring.
Adding node 127.0.0.1:8126 to the ring.
```

I reverted 40647cb to go back to hashring v1.0.1, and now proxy.js works.

### Configs

Here's my proxy config:
```
{"nodes":[{"host":"127.0.0.1","port":8126,"adminport":8127},{"host":"127.0.0.1","port":8128,"adminport":8129}],"port":8125,"udp_version":"udp4"}
```

And here's a worker config (other worker is the same except for ports):

```
{"graphitePort":2003,"graphiteHost":"localhost","port":8126,"mgmt_port":8127,"deleteGauges":true,"flush_counts":false,"deleteIdleStats":true}
```

**Comment by mrtazz** [comment]
ugh, thanks for filing this bug. We will look into it.

**Comment by mindscratch** [comment]
I have the same problem while using node v0.12.2.

**Comment by martin-magakian** [comment]
+1

**Comment by tuxinaut** [comment]
:+1:  with Nodejs *v0.10.38*

**Comment by mrtazz** [comment]
fixed with https://github.com/etsy/statsd/pull/538
