### ISSUE TITLE
what do exactly legacy namespace do

### ISSUE THREAD

**Issue by andyxning** [etsy/statsd#515]
Today, i have configured a statsd to work with Graphite. However, i took me about two hours to make it work properly. The main reason  for not sending metrics from statsd to Graphite is that the configuration is not correctly and finally it works out that the main problem is about legacy namespace and prefixes.

I have read the doc in github about namespace. However, i can not make myself understood. Here is my question:

*  what does exactly legacy namespace do, what are the impacts with metric names sent to Graphite when legacy namespace is True and when legacy namespace is False. Examples is welcome.
  
* what is the relationship about legacy namespace and prefixes. Do i need to change legacy namespace value when i need to customize prefixes.

*  if i choose to change the prefixes(anyone), should i change the value of legacy namespace.

**Comment by giladegozi** [comment]
+1 on this question - can anyone help us make some sense out of it please?

**Comment by andyxning** [comment]
I think the doc does not explain it clearly. Example is good. :)​

++++++
Ning Xie


2015-06-09 23:05 GMT+08:00 giladegozi <notifications@github.com>:

**Comment by pathzzrd** [comment]
The legacy namespacing should not be used when starting out with statsd. We continue to maintain it as migrating to the new namespacing is costly for early adopters of statsd
