### ISSUE TITLE
Missing explanation for the metric graphiteStats.calculationtime

### ISSUE THREAD

**Issue by tuxinaut** [etsy/statsd#535]
On the **TCP Stats Interface** wiki site the explanation for the `graphiteStats.calculationtime` metric is missing.

**Comment by benburry** [comment]
graphiteStats.calculationtime is the number of milliseconds taken to build the set of metric values to be flushed to Graphite. 

You can see the metric being added [here](https://github.com/etsy/statsd/blob/b5218765607df7570324b12809426cff2de1d248/backends/graphite.js#L234) and [here](https://github.com/etsy/statsd/blob/b5218765607df7570324b12809426cff2de1d248/backends/graphite.js#L241).

I'm strugging to find the TCP Stats Interface wiki page you're referring to. Can you link to it, or open a PR with the change?

**Comment by manteca** [comment]
Here
[https://github.com/etsy/statsd/blob/master/docs/admin_interface.md](https://github.com/etsy/statsd/blob/master/docs/admin_interface.md)
