### ISSUE TITLE
TCP/UDP use cases

### ISSUE THREAD

**Issue by goncalopereira** [etsy/statsd#543]
More of a question on the direction of StatsD than an issue.

I see StatsD on its own field with fast, lightweight metrics - If there are delivery issues then it would be a problem of having less network noise or using sample rates.

Slower and more accurate counters seem more of a BI, logging concern.

Any thoughts on why TCP was added ? 

Many Thanks

**Comment by pathzzrd** [comment]
@goncalopereira TCP was added for our particular use case of fronting etsy/statsd with https://github.com/uber/statsrelay. That's not to say it wasn't also a highly requested feature but we agree with you that slower accurate counters are indeed more of a logging concern. For those cases we point people towards https://github.com/etsy/logster.
