### ISSUE TITLE
Set a text value for a metric

### ISSUE THREAD

**Issue by pihomeserver** [etsy/statsd#547]
Hello,
Is it possible to send a text as a metric value (for a set for exemple) ?

**Comment by yyjinlong** [comment]
no，must be int、float or double type

**Comment by pihomeserver** [comment]
Thank you

**Comment by pathzzrd** [comment]
Hi, @pihomeserver as you might already have gathered statsd does not do this currenty. However, I was wondering if you'd like to share your use case as this might be a useful feature to develop in future versions of statsd.

**Comment by pihomeserver** [comment]
I do not have a lot of examples. I collect data to display them in a dashboard framework. Then most of my data are numerical but i have an option to store a text information based on a date like the ephemeris for example (today it's the day for Theodore, Teddy, Dorine). Storing text with stastd could help sometimes to not store the information in a different way than other statistics.

A real example in my project is about financial operations. Each time a transaction is validated by a banking back end system, i would like to store the instrument type. I can have shares, bonds, swaps, options, warrants, funds transfer, position transfer, etc. 
Currently I should have one series per instrument but the consolidation would be more complex and i would also need to maintain somewhere the list of available series to do the consolidation based on time.

Well i have that in mind : all timestamped data should not be only numerical. But not sure it makes sense for statsd team or that my approach is correct.

**Comment by pathzzrd** [comment]
>all timestamped data should not be only numerical. But not sure it makes sense for statsd team or that my approach is correct.

I'm all for experimentation. I think text sets could provide some non-traditional statsd usage for things like language processing. Just for reference, what backend were you looking to sync this data to?

**Comment by pihomeserver** [comment]
Currently i test influxdb because it's a time series database that i like but in near futur i plan to use MSSQL also because it's more "famous" in companies world

**Comment by pathzzrd** [comment]
Thanks @pihomeserver, that's some good information. Please note, I am not sure if there is a statsd backend plugin for MSSQL. Unless my google-fu is failing me, it is likely that one will need to be written. Thanks for chatting.
