### ISSUE TITLE
how does statsd collect datas

### ISSUE THREAD

**Issue by puddean** [etsy/statsd#563]
I'm a new one here and i'm sorry to ask this kind of stupid question, but i'm very confused.
i just run statsd with graphite and they indeed work
my question is that how can statsd collect the data i want to inspect? For example,i use python_example in the statsd/examples as client. and i want to monitor the apache's activity on my server. What should i do ? should i just send
```  
client.gauges('apache.total_accesses', 50) 
```
something like this? if so, how does statsd manage to collect it?

please give me some explanations , please !

**Comment by brange** [comment]
Statsd doesn't collect any data. You'll have to feed your data to statsd.
See example in the README.md https://github.com/etsy/statsd#usage,

So you'll have to send your apache access data to statsd somehow.

**Comment by dminear** [comment]
An example of how I use Apache with a perl handler to check on hacker attemps is at https://github.com/dminear/apache_hack_check . It is a perl handler that uses redis to block out IP's that access certain paths that don't exist, so the request must be nefarious. The script also sends updates to statsd to track good and bad request levels. See http://www.scrappintwins.com/nop/ for the real-time graphs.

**Comment by pathzzrd** [comment]
@puddean, @brange is right statsd itself doesn't collect any data.

However, if you are looking to get apache stats into graphite a quick google turns up https://github.com/jib/mod_statsd which while I've never tried it, might prove useful to you.

**Comment by puddean** [comment]
thanks to you guys. The comments are very useful. I'm getting more clear about statsd !
