### ISSUE TITLE
How can I send multiple tags in statsd

### ISSUE THREAD

**Issue by byteshiva** [etsy/statsd#567]
I wanted to execute the below command

```
echo "cpu_load_short,host=server01,region=us-west|c" | nc -u -w1  127.0.0.1 8125
```
throws

```
DEBUG: Bad line: 1 in msg "cpu_load_short,host=server01,region=us-west|c"
```

**Comment by johndodev** [comment]
This repo seems not really maintained anymore, but you need this PR to be merged for that : https://github.com/etsy/statsd/pull/539

There are some fork you can use, like https://github.com/johndodev/etsy-statsd 

and if you need the influxDb backen, I also forked it to allow tags: https://github.com/johndodev/statsd-influxdb-backend

**Comment by johndodev** [comment]
As @pathzzrd says, we missed the ```keyNameSanitize: false``` option. My first fork of etsy-statsd is useless now, I will remove it soon.
