### ISSUE TITLE
Update debian changelog for next release

### ISSUE THREAD

**Issue by pathzzrd** [etsy/statsd#568]
Just as a reminder. Thanks @volans-  :)

**Comment by wido** [comment]
Any news on the new release? I would love a new release with the recent IPv6 code in there.

Use-case is to run statsd in a IPv6-only environment. Works fine with the current master and NodeJS 0.12

**Comment by pathzzrd** [comment]
@wido the new release will be out when i get a couple free days away from a project I've been assigned. We've been running the current master in production now for a few weeks and things have been stable for us as well.

**Comment by wido** [comment]
@pathzzrd Great! We are running it in production as well: https://hub.docker.com/r/pcextreme/statsd/

Would like to update that Docker image so that it points to a official release instead of cloning master.
