### ISSUE TITLE
Offline debian package installation

### ISSUE THREAD

**Issue by banjoh** [etsy/statsd#577]
Hola good people,

I have a setup that has not external connection to the internet. When I build and install statsd debian package, I noticed it has a dependency to npm and requires installation of certain packages from npm repositories. Which ones are they and are they required? StatsD seems to work without them if I run it using the instructions in the ReadMe. Thanks in advance.

Evans

**Comment by pathzzrd** [comment]
hi @banjoh 

you can find out which packages are required by statsd by running `npm view statsd dependencies`. The dependencies are used for the syslog backend, the repeater backend, the proxy server, and windows service management.

If you aren't using any of that functionality it should work out of the box without the dependencies!
