### ISSUE TITLE
Error on start up of statsD

### ISSUE THREAD

**Issue by jameshd** [etsy/statsd#587]
Hi,

I'm having a problem sending metrics to graphite via StatsD. I've followed the [DO tutorials](https://www.digitalocean.com/community/tutorials/how-to-configure-statsd-to-collect-arbitrary-stats-for-graphite-on-ubuntu-14-04) to get graphite installed, then paused when it came to installing StatsD. I followed the repo instructions for that part, clone, copy config etc. I'm using AWS Ubuntu based box. 

Graphite and Carbon seem to be working. Manually pushing metrics in via the command line worked fine. e.g. 
`echo "foo.bar 1 `date +%s`" | nc localhost 2003`

That appeared in Graphite no problem. StatsD is installed on the same box. 

Now here's the thing. It worked in the past and the StatsD daemon itself is able to push metrics into graphite...

I start the StatsD daemon with npm start. My config is called config.js and looks like this:
``` 
{
  debug: true, 
  dumpMessages: true,
  graphitePort: 2003
, graphiteHost: "localhost"
, port: 8125
, backends: [ "./backends/console", "./backends/graphite" ]
}
```

Whenever I run a "stats" ` echo "stats" | nc localhost 8126` everything looks fine. However, there's nothing in the syslog related to any of this and the daemon just sits there flushing metrics out or appearing to. 

```
ubuntu@ip-...-31-30-0:~/build/statsd$ npm start

> statsd@0.8.0 start /home/ubuntu/build/statsd
> node stats.js config.js

12 Sep 09:57:21 - [3506] reading config file: config.js
12 Sep 09:57:21 - DEBUG: Loading server: ./servers/udp
12 Sep 09:57:21 - server is up INFO
12 Sep 09:57:21 - DEBUG: Loading backend: ./backends/console
12 Sep 09:57:21 - DEBUG: Loading backend: ./backends/graphite
Flushing stats at  Mon Sep 12 2016 09:57:31 GMT+0000 (UTC)
{ counters: 
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  timers: {},
  gauges: {},
  timer_data: {},
  counter_rates: 
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }
12 Sep 09:57:31 - DEBUG: numStats: 3
```

`npm test` ran fine too here's an example of a counter I'm trying to send

`echo "a.counter:15|c" | nc localhost 8125`

Can anyone offer some direction?

**Comment by benburry** [comment]
Hi. In your example you're starting statsd on port 8125 and sending your
metrics to port 8126

Is that the problem? Do things work correctly with a netcat to port 8125?

**Comment by benburry** [comment]
I see that I misread your original comment. Please ignore.

**Comment by benburry** [comment]
Are you still experiencing this issue?

**Comment by jameshd** [comment]
seems to be behaving as expected now.. will re-open if anything else happens.

**Comment by za3k** [comment]
I realize this is closed, but pass the -u option to nc to use UDP, the default statsd server.
