### ISSUE TITLE
Statsd sending metrics that no longer exist

### ISSUE THREAD

**Issue by 326TimesBetter** [etsy/statsd#590]
We are using statsd to collect metrics and send them to elasticsearch for analysis. We noticed that we were receiving a HUGE amount of metrics and when we dug deeper into why we have noticed that it is because statsd continually sends metrics that are no longer being sent to IT. We're still seeing metrics pump out of statsd representing old metrics from old pieces of infrastructure that no longer exist. Restarting our statsd instances appears to drop these.

What could cause something like this??

**Comment by Elufimov** [comment]
I see it too in the same configuration.

**Comment by benburry** [comment]
The [deleteIdleStats](https://github.com/etsy/statsd/blob/master/exampleConfig.js#L61) config variable controls whether statsd continues to emit all metrics it has encountered, versus emitting only metrics it's encountered during this flush interval.

To stop statsd from sending zeroes for all metrics it's ever encountered, you can set [deleteIdleStats](https://github.com/etsy/statsd/blob/master/exampleConfig.js#L61) to true
