### ISSUE TITLE
graphite documentation aggregation needs update

### ISSUE THREAD

**Issue by tehlers320** [etsy/statsd#592]
The docs show to use a regex which does not catch all of the "sum_95" "sum_99" metrics that stats.timers emits

https://github.com/etsy/statsd/blob/cluster_proxy/docs/graphite.md

perhaps 

```
[max]
pattern = \.(max_..|max)$
xFilesFactor = 0.0
aggregationMethod = max
```

**Comment by tehlers320** [comment]
I wasnt looking at master nevermind..

`\.upper(_\d+)?$`

**Comment by tehlers320** [comment]
Should they all have the same regex as upper?

**Comment by benburry** [comment]
@tehlers320 could you explain your question?

**Comment by tehlers320** [comment]
I guess it is, should all of the timer metrics with 99th percentile also have the same regex as upper?

so for example count_99.wsp will get an average by graphite instead of a sum.

**Comment by benburry** [comment]
That really depends on what you want to do with the data. Average is a sensible default, but if you want to sum or max the counts over the time period, that's able to be your implementation choice
