### ISSUE TITLE
statsd rejects metricts that were send via TCP protocol

### ISSUE THREAD

**Issue by vinod-990** [etsy/statsd#627]
Hi,

I have an issue with TCP configuration, while everything works if I use UDP transport. Here is test configuration

tcp6       0      0 :::8126                 :::*                    LISTEN      15392/statsd config 
udp        0      0 0.0.0.0:8125            0.0.0.0:*                           15392/statsd config

{
  dumpMessages: true
, debug: "True"
, port: 8125
, backends: [ "./backends/console" ]
}

Here is an example with UDP:

Client Part:
```
>>> import statsd
>>> c = statsd.StatsClient('localhost', 8125)
>>> c.incr('foo')
```

Server Part:
```
2 Aug 12:18:44 - DEBUG: foo:1|c
Flushing stats at  Wed Aug 02 2017 12:18:48 GMT+0000 (UTC)
{ counters: 
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 1,
     'statsd.metrics_received': 1,
     foo: 1 },
  timers: {},
  gauges: { 'statsd.timestamp_lag': 0 },
  timer_data: {},
  counter_rates: 
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0.1,
     'statsd.metrics_received': 0.1,
     foo: 0.1 },
  sets: {},
  pctThreshold: [ 90 ] }
```
Here is an example with TCP:

Client Part:
```
>>> import statsd
>>> c = statsd.TCPStatsClient('localhost', 8126)
>>> c.incr('foo')
```

Server Part:
```
Flushing stats at  Wed Aug 02 2017 12:19:18 GMT+0000 (UTC)
{ counters: 
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0,
     foo: 0 },
  timers: {},
  gauges: { 'statsd.timestamp_lag': 0 },
  timer_data: {},
  counter_rates: 
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0,
     foo: 0 },
  sets: {},
  pctThreshold: [ 90 ] }
```
```
0000  00 00 03 04 00 06 00 00 00 00 00 00 00 00 08 00   ................
0010  45 00 00 3a 5d e1 40 00 40 06 de da 7f 00 00 01   E..:].@.@.......
0020  7f 00 00 01 1f be c0 00 ea 70 d7 de 00 d9 c5 f7   .........p......
0030  80 18 01 56 fe 2e 00 00 01 01 08 0a 04 9f 8a 3e   ...V...........>
0040  04 9f 8a 3e 45 52 52 4f 52 0a                     ...>ERROR.
```
Here is the link to tcpdump:
https://drive.google.com/open?id=0BylkK99zMxQkM1Qxa2hKS09qbFE

As you can see in case of using TCP, statsd do not print and do not handle metric. According to the dump statsd receives the metric, but sends ERROR reply. Please advice what can be the root of the issue.

**Comment by benburry** [comment]
Can you post the statsd config you were using for the TCP tests?

**Comment by vinod-990** [comment]
[config.txt](https://github.com/etsy/statsd/files/1195040/config.txt)

**Comment by benburry** [comment]
It looks like you're not enabling the tcp server in your config (it's disabled by default). 

For an example of how to enable it, see the servers: configuration setting in the config file comments and this link https://github.com/etsy/statsd/blob/master/docs/server.md

**Comment by vinod-990** [comment]
I sent requests to management tcp port by mistake. Thank you for your help. Sorry for disturbing.
