### ISSUE TITLE
Documentation around configuration file?

### ISSUE THREAD

**Issue by TannerMoore** [etsy/statsd#631]
I am trying to setup my statsd instance to write to influxdb and I cannot figure out how to do it. The example config assumes graphite will be used, and I can't find a single document on how to get statsd pointed at influxdb

**Comment by grahamb** [comment]
Have you looked at https://github.com/etsy/statsd/blob/master/docs/backend.md & https://github.com/bernd/statsd-influxdb-backend?

**Comment by TannerMoore** [comment]
This looks good. I went with Telegraf soon after I wrote this issue since it had easy support for InfluxDB. I will reopen this issue if needed.
