### ISSUE TITLE
statsd repeater resource usage

### ISSUE THREAD

**Issue by dansajner** [etsy/statsd#634]
Hi.  I configured a statsd instance with the repeater backend forwarding to an existing statsd instance with a graphite backend.  Both servers have 2 CPU and 2G RAM.  The existing statsd host uses negligible resources, but the statsd repeater uses an entire CPU and all available RAM as traffic ramped up.  Is there a known resource constraint with the repeater backend?

Current node version is `v0.10.40`.
The configuration of the repeater looks like:
```
{
  port: "8125"
, address: "1.2.3.4"
, backends: ["./backends/repeater"]
, debug: false
, keyNameSanitize: true
, mgmt_address: "1.2.3.4"
, mgmt_port: "8126"
, title: "statsd"
, healthStatus: "up"
, dumpMessages: false
, flushInterval: "10000"
, percentThreshold: [75, 90, 99]
, flush_counts: true
, prefixStats: "statsd"
, repeater: [{"host":"XXXstatsd1","port":8125}]
}
```

**Comment by dansajner** [comment]
Upgrading the v0.8.0 and using a TCP connection from repeater -> statsd resolved the memory issue.

**Comment by gagado** [comment]
How does the repeater start working? thank you.

**Comment by gagado** [comment]
@dansajner  How does the repeater start working?
