### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by steevhise** [etsy/statsd#646]

**Comment by tomh05** [comment]
It's broken in node 8. They released a fix for it in codebase 2 years but haven't tagged a new version since.

**Comment by tomh05** [comment]
@benburry is anyone at Etsy still involved with this project?

**Comment by steevhise** [comment]
@mrtazz or @draco2003  or @SaveTheRbtz or any major contributors, does anybody know if this is still being worked on at all, or has been forked off to something that's still maintained?  anybody? thanks for any clues you can provide...

**Comment by SaveTheRbtz** [comment]
Have no idea, haven't used/committedto statsd it in years.

**Comment by enys** [comment]
Same question, thanks for asking!

**Comment by acanimal** [comment]
Any good alternative project for node?

**Comment by mediocretes** [comment]
@acanimal I'm trying to make this the least like an ad that I possibly can.  I'm here because I needed to look some stuff up for our statsd backend library.  We also have a node library (https://github.com/Instrumental/instrumental_agent-node) and offer free accounts up to a certain level of usage.  All our libraries are open source, but the platform itself is only available via SaaS.

**Comment by acanimal** [comment]
Thanks @mediocretes !

**Comment by steevhise** [comment]
FWIW, after waiting for an answer to this for a couple months we have switched to using Elasticsearch APM Server, sending data to that with the **elastic-apm-node** library.  It's super easy to set up in a node app, and there seems to be a lot of support and community involvement with it.

**Comment by buzzdan** [comment]
any updates on this project ? is it... dead ?

**Comment by mrtazz** [comment]
Hi everyone! Sorry for the lack of response here. I've been working on some ways to give the project the attention it deserves again and a full write up is here https://github.com/etsy/statsd/issues/649. I will close this issue as I hope this answers the question and thank you all for the interest in keeping statsd alive!
